name: asistiot_project

description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.2 # Cupertino icons for iOS
  flutter_blue_plus: ^1.31.18  # For Bluetooth functionality
  permission_handler: ^11.3.1 # For handling permissions
  lottie: ^3.1.2 # Animation library for Flutter
  amplify_flutter: ^1.0.0 # Core Amplify library
  amplify_auth_cognito: ^1.0.0 # Authentication with Cognito
  amplify_secure_storage_dart: ^0.4.4 # Secure storage for sensitive data
  amplify_api: ^1.0.0 # API interactions
  intl: ^0.20.2 # Internationalization support
  http: ^1.4.0 # HTTP requests
  record: ^6.0.0 # Microphone stream for audio input
  googleapis_auth: ^2.0.0 # Dialogflow integration for voice commands
  path_provider: ^2.1.5 # File system access
  hive: ^2.2.3 # Local database for storing routines
  hive_flutter: 1.1.0 # Flutter integration for Hive
  flutter_background_service: ^5.1.0 # Background service for running tasks
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1 # Code generation for Hive
  build_runner: ^2.4.9 # Build runner for code generation

flutter:
  uses-material-design: true
  assets:
    - assets/

